source 'http://rubygems.org'

gem 'watir-webdriver'
gem 'rest-client'
gem 'nokogiri', '~> 1.8.0'
gem 'pry'
gem 'bundler'
gem 'sentimental'
gem 'mustache', '~> 1.0'
gem 'smarter_csv'
gem 'builder'
gem 'rake'
